# Notebook 3 - NumPy
[NumPy](http://numpy.org) short for Numerical Python, has long been a cornerstone of numerical computing on Python. It provides the data structures, algorithms and the glue needed for most scientific applications involving numerical data in Python. All computation is done in vectorised form - using vectors of several values at once instead of singular values at a time. NumPy contains, among other thigs:
* A fast and efficient multidimensional array object `ndarray`.
* Mathematical functions for performing element-wise computations with arrays or mathematical operations between arrays.
* Tools for reading and manipulating large array data to disk and working with memory-mapped files.
* Linear algebra, random number generation and Fourier transform capabilities.

For the rest of the course, whenever array is mentioned it refers to the NumPy ndarray.
<br>

## Table of contents
- [The ndarray](#ndarray)
    - [Creating arrays](#creating)
    - [Data Types](#data)
    - [Arithmetic Operations](#arithmetic)
    - [Indexing and Slicing](#indexing)
- [Functions with ndarrays](#functions)
    - [Universal Functions](#universal)
    - [Whole-Array Functions](#whole)
    - [Liear algebra](#linear)
- [File IO](#file)

# Why NumPy?
Is the first question that anybody asks when they find out about it. 

Some people might say: *I don't care about speed, I want to spend my time researching how to cure cancer, not optimise coputer code!*

That's perfectly reasonable, but are you willing to wait a lot longer for your experiment to finish? I definitely don't want to do that. Let's see how much faster NumPy really is!

to show that we'll be using the magic command `%timeit` which you can read more about [here](https://ipython.readthedocs.io/en/stable/interactive/magics.html) and don't worry about the details now, they will clear up later.

Let's have a look at generating a vector of 10M random values and then summing them all up using the Python way and using the NumPy way!

In [1]:
import numpy as np

x = np.random.randn(10000000) # generate random numbers

print("Running normal python sum()")
%timeit sum(x)

print("Running numpy sum()")
%timeit np.sum(x)

Running normal python sum()
891 ms ± 35.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Running numpy sum()
12.4 ms ± 71.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**WOW** that was a difference of more than a **100 times** and that was just for a single summing operation. Imagine if you had several of those running all the time!

Are you onboard with Numpy then? Let's proceed...

# The ndarray <a name="ndarray"></a>
The ndarray is a backbone on Numpy. It's a fast and flexible container for N-dimensional array objects, usually used for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

Here is a quick example of its capabilities:

In [2]:
import numpy as np

# create a 2x3 array of random values
data = np.random.randn(2,3)
data

array([[ 1.0129896 , -1.2802655 , -2.60988511],
       [-0.26117818,  0.32963863, -1.10865483]])

In [3]:
data * 10 #multiply all numbers by 10

array([[ 10.12989597, -12.802655  , -26.09885107],
       [ -2.61178177,   3.29638632, -11.08654833]])

In [4]:
data + data #element-wise addition

array([[ 2.02597919, -2.560531  , -5.21977021],
       [-0.52235635,  0.65927726, -2.21730967]])

Every array has a shape, a tuple indicating the size of each dimnesion and a dtype. You can obtain these via the respective methods:

In [5]:
# number of dimensions of the array
data.ndim

2

In [6]:
# the size of the array
data.shape

(2, 3)

In [7]:
# the type of values store in the array
data.dtype

dtype('float64')

## Creating arrays <a name="creating"></a>
The easiest and quickest way to create an array is from a normal Python list.

In [8]:
data = [1.2, 5.2, 5, 7.8, 0.3]
arr = np.array(data)

arr

array([1.2, 5.2, 5. , 7.8, 0.3])

It is also possible to create multidimensional arrays in a similar fashion. An example would be:
```python
data = [[1.2, 5.2, 5, 7.8, 0.3],
        [4.1, 7.2, 4.8, 0.1, 7.7]]
```
Try creating an multidimensional array below and verify its number of dimensions

In [9]:
ident = [[1, 0], [0, 1]]
idarray = np.array(ident)

idarray.ndim

2

We can also create an array filled with zeros

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Again, it is also possible to create a multidimensional array by passing a tuple as an argument

In [11]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

NumPy also has an equivalent to the built-in Python function `range()` but it's called `arange()`

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here is a summary of the most often used methods to create arrays. Use it as a future reference!

| Function | Description |
|----|:--|
| array  | Convert input data to an ndarray either by inferring a dtype<br>or explicitly specifying a dtype; copies the input data by default. |
| arange | Similar to the built-in `range` function but returns an ndarray. |
| ones | Produces an array of all 1s with the given shape and dtype. |
| ones_like | Similar to `ones` but takes another array and produces a ones array<br>of the same shape and dtype |
| zeros, zeros_like | Similar to `ones` but produces an array of 0s. |
| eye | Create a square NxN identity matrix (1s on the diagonal and 0s elsewhere). |

## Data Types <a name="data"></a>
The data type or `dtype` is a special object containing the information the array needs to interpret a chunk of memory. We can specify it during the creation of an array 

In [13]:
arr = np.array([1, 2, 3], dtype=np.float64)

In [14]:
# you can check the type of an array with
arr.dtype

dtype('float64')

Similar to normal Python, NumPy has several types of data like int, float and bool. However, it also extends these by specifying the number of bits used per variable like 16, 32, 64 or 128.

To keep things simpe, you can use:
- `np.int64` to store integer numbers
- `np.float64` to store numbers with a fraction value
- `np.bool` to store `True` and `False` values

When creating arrays in NumPy the type is inferred (guessed) so you don't need to explicitly specify it.

It is not necessary for this course but if you want to learn more about datatypes in NumPy you can go to https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html

Similar to normal Python, you can cast(convert) an array from one dtype to another using the `astype` method:

In [15]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [16]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

The normal limitations to casting apply here as well. You can try creating a `float64` array and then converting it to an `int64` array below 

### Exercise 1
Create a 5x5 [identity matrix](https://en.wikipedia.org/wiki/Identity_matrix). Then convert it to `int64` dtype. At the end confirm its properties using the appropriate attributes.

In [17]:
M = np.eye(5)
M = M.astype("float64")
M

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Arithmetic operations <a name="arithmetic"></a>
You have already gotten a taste of this in the examples above but let's try to extend that.

Arrays are important because they enable you to express batch operations on data without having to write for loops - this is called **vectorisation**.

Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
A * A

array([[ 1,  4,  9],
       [16, 25, 36]])

In [20]:
A - A

array([[0, 0, 0],
       [0, 0, 0]])

Arithmetic operations with scalars propogate the scalar argument to each element in the array:

In [21]:
A * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [22]:
A ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparisons between arrays of the same size yield boolean arrays:

In [23]:
B = np.array([[1, 7, 4],[4, 12, 2]])
B

array([[ 1,  7,  4],
       [ 4, 12,  2]])

In [24]:
A > B

array([[False, False, False],
       [False, False,  True]])

Arithmetic operations with differently sized arrays is called **broadcasting** but will not be covered in this course due to the limited time.

### Exercise 2
Generate a vector of size 10 with values ranging from 0 to 0.9, both included.

In [25]:
G = np.arange(0, 1, 0.1)
G

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### Exercise 3
Change the value of `c` so that the following code runs properly.

_Hint: What happens when you obtain `a*b`? What are the dimensions of this object? Use .dim, and comment out some lines, to play with this code and figure this out._

In [26]:
a = np.asarray([[3], [7], [878], [26]])
b = np.asarray([1, 10, 11, 101, 110])
c = np.asarray([0, 1, 2, 3, 4]) # Change this variable

(a*b) + c

array([[    3,    31,    35,   306,   334],
       [    7,    71,    79,   710,   774],
       [  878,  8781,  9660, 88681, 96584],
       [   26,   261,   288,  2629,  2864]])

## Indexing and slicing <a name="indexing"></a>
NumPy offers many options for indexing and slicing. Coincidentally, they are very similar to Python.

Let's see how this is done in 1D:

In [27]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
A[5]

5

In [29]:
A[5:8]

array([5, 6, 7])

In [30]:
A[5:8] = 0
A

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

**Important:** Unlike vanilla Python, NumPy array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [31]:
A_slice = A[5:8]
A_slice

array([0, 0, 0])

In [32]:
A_slice[:] = [12, 17, 24]
A_slice

array([12, 17, 24])

Here we used the [:] operator which assings to all values in the array.
Let's now have a look at higher dimensional arrays:

In [33]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now that we have 2 dimensions, we need to input 2 indices to get a specific element of the array. Alternatively, if we input only one index, then we obtain the whole row of the array:

In [34]:
C[2]

array([7, 8, 9])

In [35]:
C[2][1]

8

In [36]:
C[2, 1]

8

Here is a picture to better explain indexing in 2D:
<img src="img/ndarray.png" alt="drawing" width="300"/>

The same concepts and techniques are extended into multidimensional arrays:
if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all data along the higher dimensions.

Now let's look into **slicing**. You already saw above that slicing in 1D is done the same way as in standard Python data structures. So how do we do that in 2D? Well, it is fairly intuitive:

In [37]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
C[:2]

array([[1, 2, 3],
       [4, 5, 6]])

This can be read as *select the first 2 rows of C*

In [39]:
C[1, :2]

array([4, 5])

In [40]:
C[:, :1]

array([[1],
       [4],
       [7]])

Here is some visual aid for what happened above:
<img src="img/indexing.png" alt="drawing" width="400"/>

### Exercise 4
Create a 2D array with 1s on the border and 0s inside

In [41]:
A = np.zeros((5,5))
A[:1] = 1
A[:, :1] = 1
A[-1:] = 1
A[:, -1:] = 1
A

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Reshaping and Transposing Arrays <a name="transposing"></a>
We can use the method `reshape()` to convert the data from one shape into another. Later we can use the `T` attribute to obtain the transpose of the array.

In [42]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
B = A.reshape((3,5))
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
B.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

 # Functions with ndarrays <a name="functions"></a>
 Now that we've seen how to create and manipulate ndarrays, we will see some of the many functions NumPy has to compute with them. In particular, we'll look at: functions which work element-wise (called ufuncs), functions which work on the whole array at once, and functions specialised for linear algebra.

## Universal Functions <a name="universal"></a>
or *ufunc* are functions that perform element-wise operations on data in ndarrays. You can think of them as fast vectorised wrappers for simply functions. Here is an example of `sqrt` and `exp`:

In [45]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.sqrt(A)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
np.exp(A)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Other universal functions take 2 arrays as input. These are called *binary* functions.

For example `maximum()` selects the biggest values from two input arrays

In [48]:
x = np.random.randn(10)
y = np.random.randn(10)
np.maximum(x, y)

array([-0.96998944, -0.23603681,  1.51041949,  0.84618698, -0.19671203,
        0.12068045,  1.45445021,  1.5061538 ,  1.56956028,  0.84439184])

Here is a list of useful *ufuncs* in NumyPy:

*Again, you don't need to memorise them. This is just a reference*
### Unary functions (accept one argument)

| Function | Description |
|----|----|
| abs, fabs | Compute the absolute value element-wise for integer, floating point, or complex values.<br>Use fabs as a faster alternative for non-complex-valued data |
| sqrt | Compute the square root of each element. Equivalent to arr ** 0.5 |
| exp | Compute the exponent ex of each element |
| log, log10, log2, log1p | Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively |
| cos, cosh, sin, sinh, tan, tanh | Regular and hyperbolic trigonometric functions |

### Binary functions (accept 2 arguments)
| Functions | Description |
| ---- | ---- |
| add | Add corresponding elements in arrays |
| subtract | Subtract elements in second array from first array |
| multiply | Multiply array elements |
| divide, floor_divide | Divide or floor divide (truncating the remainder) |
| mod | Element-wise modulus (remainder of division) |
| power | Raise elements in first array to powers indicated in second array |
| maximum | Element-wise maximum. fmax ignores NaN |
| minimum | Element-wise minimum. fmin ignores NaN |

## Whole-Array Functions <a name="whole"></a>
As wll as ufuncs, which operate element-by-element, there are many functions which work on the whole of an array at once.

NumPy offers a set of mathematical functions that compute statistics about an entire array:

In [49]:
B = np.random.randn(5, 4)
B

array([[-1.36817751,  0.10415951,  0.41741558,  0.69219411],
       [-0.97037186,  0.21398241,  0.42186989, -0.04023288],
       [-0.32459601, -0.01309487, -0.13173495,  1.15416256],
       [-0.53883387,  1.36392203,  0.85208129, -0.60652098],
       [ 1.51454193, -2.18692352,  0.32870556, -1.71727862]])

In [50]:
B.mean()

-0.04173651066032871

In [51]:
np.mean(B)

-0.04173651066032871

In [52]:
B.sum()

-0.8347302132065743

In [53]:
B.mean(axis=1)

array([-0.03860208, -0.09368811,  0.17118418,  0.26766212, -0.51523867])

Here `mean(axis=1)` means compute the mean across the columns (axis 1)

Here is a set of other similar functions:

| Function | Description|
| --- | --- |
|sum | Sum of all the elements in the array or along an axis. Zero-length arrays have sum 0. |
| mean | Arithmetic mean. Zero-length arrays have NaN mean. |
| std, var | Standard deviation and variance, respectively, with optional<br>degrees of freedom adjustment (default denominator n). |
|min, max | Minimum and maximum. |
| argmin, argmax | Indices of minimum and maximum elements, respectively. |

Similar to Python's built-in list type, NumyPy arrays can be sorted in place:

In [54]:
A = np.random.randn(10)
A

array([-0.50684001,  0.50043512,  0.01853705,  1.76282885, -0.08361955,
       -0.75643401, -0.53478528, -1.83564091, -0.36795901, -0.02176345])

In [55]:
A.sort()
A

array([-1.83564091, -0.75643401, -0.53478528, -0.50684001, -0.36795901,
       -0.08361955, -0.02176345,  0.01853705,  0.50043512,  1.76282885])

Another option is `unique()` which returns the sorted unique values in an array.

### Exercise 5
Create a random vector of size 30 and find its mean value

In [56]:
x = np.random.rand(30)
np.mean(x)

0.5094568815962195

### Exercise 6

Subrtract the mean of each column of a randomly generated matrix:

In [57]:
x = np.random.randn(5,5)
print(x)
print(x.mean(axis=0))
x = x - x.mean(axis=0)
x

[[-0.18414028 -0.63355234 -0.30205928  0.26474567 -1.76394873]
 [ 0.70649125  0.65433725  0.41798621 -1.07012084  0.22465425]
 [-0.431986    0.27822972 -0.14490046  0.33644042 -1.60520653]
 [ 0.69594485  2.69317369  0.21096538  0.53889836  0.99055104]
 [-0.25126018 -0.98116754 -0.26537323 -0.08577975 -0.19730332]]
[ 0.10700993  0.40220416 -0.01667628 -0.00316323 -0.47025066]


array([[-0.2911502 , -1.0357565 , -0.285383  ,  0.26790889, -1.29369808],
       [ 0.59948132,  0.25213309,  0.43466248, -1.06695761,  0.69490491],
       [-0.53899593, -0.12397444, -0.12822418,  0.33960365, -1.13495587],
       [ 0.58893492,  2.29096954,  0.22764165,  0.54206159,  1.46080169],
       [-0.35827011, -1.3833717 , -0.24869695, -0.08261652,  0.27294734]])

## Linear Algebra <a name="linear"></a>
Similar to other languages like MATLAB, NumyPy offers a set of standard linear algebra operations, like matrix multiplication, decompositions, determinants and etc.. Unlike some other languages though, the default operations like `*` peform element-wise operations. To perform matrix-wise operartions we need to use special functions:

In [58]:
temp = np.arange(16)
A = temp[:8]
B = temp[8:]

In [59]:
A.dot(B)

364

We can also extend this with the `numpy.linalg` package:

In [60]:
from numpy.linalg import inv, qr
A = np.random.randn(5, 5)
mat = A.T.dot(A)
mat

array([[ 3.36377336, -2.22897347, -0.41681716, -1.24092352, -0.78149405],
       [-2.22897347,  5.63753686,  2.95531891, -1.74406854,  2.36131729],
       [-0.41681716,  2.95531891,  5.59474656, -1.42431877,  1.29588374],
       [-1.24092352, -1.74406854, -1.42431877,  4.46619931, -3.19710807],
       [-0.78149405,  2.36131729,  1.29588374, -3.19710807,  3.64208096]])

In [61]:
inv(mat)

array([[ 2.00649685,  0.73406821, -0.12743889,  2.16215261,  1.89794763],
       [ 0.73406821,  0.58972573, -0.18382744,  0.70369077,  0.45829152],
       [-0.12743889, -0.18382744,  0.26339916, -0.06603636, -0.05984982],
       [ 2.16215261,  0.70369077, -0.06603636,  2.96201645,  2.63133479],
       [ 1.89794763,  0.45829152, -0.05984982,  2.63133479,  2.71583287]])

In [62]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.66533454e-16, -1.38777878e-17,
         4.44089210e-16,  0.00000000e+00],
       [ 8.88178420e-16,  1.00000000e+00, -2.77555756e-17,
         1.77635684e-15,  8.88178420e-16],
       [ 0.00000000e+00,  1.11022302e-16,  1.00000000e+00,
         4.44089210e-16, -4.44089210e-16],
       [-8.88178420e-16, -2.22044605e-16, -8.32667268e-17,
         1.00000000e+00,  0.00000000e+00],
       [ 8.88178420e-16,  0.00000000e+00,  5.55111512e-17,
         0.00000000e+00,  1.00000000e+00]])

Here is a set of commonly used `numpy.linalg` functions

| Function | Description |
| --- | --- |
| diag | Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array,<br>or convert a 1D array into a square matrix with zeros on the off-diagonal |
| dot | Matrix multiplication |
| trace | Compute the sum of the diagonal elements |
| det | Compute the matrix determinant |
| eig | Compute the eigenvalues and eigenvectors of a square matrix |
| inv | Compute the inverse of a square matrix |
| pinv | Compute the Moore-Penrose pseudo-inverse inverse of a square matrix |
| qr | Compute the QR decomposition |
| svd | Compute the singular value decomposition (SVD) |
| solve | Solve the linear system Ax = b for x, where A is a square matrix |
| lstsq | Compute the least-squares solution to y = Xb |

### Exercise 7
Obtain the digonal of a dot product of 2 random matrices

In [63]:
x = np.random.randn(5, 5)
y = np.random.randn(5, 5)

prod = np.dot(x, y)

np.diag(prod)

array([-0.90156243, -3.12041556, -2.43830701, -0.68818682, -1.79121284])

## File IO <a name="file"></a>
NumPy offers its own set of File IO functions.

The most common one is `genfromtxt()` which can load the common `.csv` and `.tsv` files.

Now let us analyse temperature data from Stockholm over the years.

First we have to load the file:

In [64]:
data = np.genfromtxt("./data/stockholm_td_adj.dat")
data.shape

(77431, 7)

The first column of this array gives years, and the 6th gives temperature readings. We can extract these.

In [65]:
yrs = data[:, 0]
temps = data[:, 5]

Having read in our data, we can now work with it - for example, we could produce a plot.
We will cover plotting in more depth in notebook 4, so there's no need to get too caught up in the details right now - this is just an examle of something we might do having read in some data. 

In [66]:
import matplotlib.pyplot as plt

plt.figure(figsize=(16, 6)) # Create a 16x6 figure
plt.plot(yrs, temps) # Plot temps vs yrs

#Set some labels
plt.title("Temperatures in Stockholm")
plt.xlabel("year")
plt.ylabel("Temperature (C)")

plt.show() # Show the plot

<Figure size 1600x600 with 1 Axes>

### Exercise 8
Read in the file `daily_gas_price.csv`, which lists the daily price of natural gas since 1997. Each row contains a date and a price, separated by a comma. Find the minimum, maximum, and mean gas price over the dataset.

_Hint: you will need to use the delimiter option in `np.genfromtxt` to specify that data is separated by commas. We will be discarding the date column..._

In [67]:
data = np.genfromtxt("./data/daily_gas_price.csv", delimiter=",")

# filter prices
data = data[1:,1]

# print stats
print("Mean: ", data.mean())
print("Std : ", data.std())
print("Max : ", data.max())
print("Min : ", data.min())

Mean:  4.331772908366535
Std :  2.2031375976175553
Max :  18.48
Min :  1.05
